# theme = "ayu_dark"
# theme = "base16_default"
# theme = "github_dark"
theme = "base16_transparent"
# theme = "hex_lavender"
# theme = "dracula"
# theme = "horizon-dark"
# theme = "kanagawa-dragon"
# theme = "doom_acario_dark"
# theme = "curzon"
# theme = "bogster"
# theme = "dracula_at_night"
# theme = "modus_vivendi_tritanopia"
# theme = "amberwood"

[editor]
line-number = "relative"
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
X = "extend_line_above"
ret = "goto_first_nonwhitespace"
S-ret = "goto_line_end"
A-l = [ "goto_last_line" , "goto_line_end"] # not working in `select` or visual mode.
C-q = "switch_to_uppercase"
C-z = "collapse_selection"
'\' =  ["flip_selections"]
'`' =  ["collapse_selection", "keep_primary_selection", "delete_selection"] # PRODUCTIVITY 1000
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode", "collapse_selection"]
D = "delete_selection_noyank"

[keys.normal.space]
"space" = ":w"
q = ":q"
x = ":bc"
e = ":wq"
n = "goto_previous_buffer"
m = "goto_next_buffer"
f = "file_picker_in_current_directory"
F = "file_picker"
K = "suspend"

[keys.insert]
C-k = "normal_mode" # doesn't work unless "rich keyboard protocol" or something like this is enabled in terminal. Will work in Kitty.
'C-]' = ["normal_mode", "goto_line_end", "append_mode", "collapse_selection"] # REQUIRES `Rich Keyboard Protocol`.
C-ret = "completion"

[keys.select]
D = "delete_selection_noyank"

[editor.lsp]
display-messages = true

